### ISSUE TITLE
[ISSUE]: Incompatibility with Fabric Loader 1.17.2

### ISSUE THREAD

**Issue by XanderCrafter** [pnk2u/More-Weapon-Variants#7]
### Where did you encounter this issue?

Singleplayer

### Mod Version

1.3.10

### Minecraft Version

1.21.5

### Minecraft Mod Loader

Fabric

### Mod Loader Version

1.17.2

### Description

The game crashes immediately due to an incompatibility with Fabric Loader 1.17.2. I have all of the More Variants series, and this one and More Torch Variants are the only two that crash the game.

### Steps to Reproduce

Start the game.
Game crashes.

### Logs

https://mclo.gs/CKNES58

### Checklist

- [x] I have searched both open and closed issues for similar issues and I couldn't find anything.

**Comment by pnk2u** [comment]
As this has been fixed, as you mentioned, this shouldn't happen and the logs don't show that either, in fact you don't even have "mstv-mweaponv" installed in those logs.  
It rather seems to me that the issue lies within nemos-moreladdervariants (also my mod, I'm sorry) being installed, please download the newest update of that mod ([1.0.7](https://modrinth.com/mod/nemos-more-ladder-variants/version/2esHuCEb)) and let me know if that fixes the issue.

**Comment by XanderCrafter** [comment]
I might have posted the wrong log. I’m troubleshooting multiple issues.

Yes, this one is fixed now, thank you!

But More Torch Variants still crashes the game.

**Comment by pnk2u** [comment]
As mWeaponV has been updated to use Fabric Loader 0.17+, I'll close this issue.
